name:                news-rest-api
version:             0.1.0.0
github:              "stanislav-az/news-rest-api"
license:             BSD3
author:              "Stanislav Zhdanovich"
maintainer:          "st.zhdanovich@gmail.com"
copyright:           "stanislav-az"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stanislav-az/news-rest-api#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- http-types
- postgresql-simple
- postgresql-simple-migration
- directory
- text
- aeson
- time
- bytestring
- configurator
- mtl

library:
  source-dirs: src

executables:
  news-rest-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - news-rest-api

tests:
  news-rest-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - news-rest-api
    - hspec
    - tasty
    - tasty-hspec
